---
apiVersion: piraeus.linbit.com/v1alpha1
kind: PiraeusControllerSet
metadata:
  name: hello-piraeus
---
apiVersion: piraeus.linbit.com/v1alpha1
kind: PiraeusNodeSet
metadata:
  name: hello-piraeus
spec:
  # etcdURL url for controller persistence.
  etcdURL: "etcd-piraeus:2379"

  # StoragePools for the NodeSet to manage.
  storagePools:
    lvmPools:
    - name: "lvm-thick"

      # piraeuspool must be an already existing lvm
      # volume group on the kubelet each Piraeus
      # node is scheduled on.
      volumeGroup: "piraeuspool"
    lvmThinPools:
    - name: "lvm-thin"
      volumeGroup: "piraeuspool"

      # piraeusthinpool must be an already existing
      # lvm thin volume backed piraeuspool on the
      # kubelet each Piraeus node is scheduled on.
      thinVolume: "piraeusthinpool"
